BukkitNo: '&6&lH&9&lK&f&lSHOP &7: &c버킷에서 해당 명령어를 사용할 수 없습니다.'
NoPerm: '&6&lH&9&lK&f&lSHOP &7: &c권한이 없습니다.'
ShopAlreadyExists: '&6&lH&9&lK&f&lSHOP &7: &c이미 해당 상점 &r{SHOPNAME} &c이 존재합니다.'
ShopDoesNotExists: '&6&lH&9&lK&f&lSHOP &7: &c해당 상점 &r{SHOPNAME} &c이 존재하지 않습니다.'
ShopCreationDone: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a의 생성이 완료되었습니다!'
ShopDeletionDone: '&6&lH&9&lK&f&lSHOP &7: &c상점 &r{SHOPNAME} &c의 삭제가 완료되었습니다!'
ShopItemSetOpen: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a의 아이템 설정창을 열었습니다!'
ShopPriceSetOpen: '&6&lH&9&lK&f&lSHOP &7: &b상점 &r{SHOPNAME} &b의 가격 설정창을 열었습니다!'
ShopLineSetDone: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a의 크기가 &6{SHOPLINE}줄 &a으로 설정되었습니다.'
ShopNPCSetPrepare: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a의 NPC를 우클릭으로 설정하세요.'
ShopNPCSetDone: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a의 NPC가 &r{SHOPNPC} &a으로 설정되었습니다.'
ShopReloadConfig: '&6&lH&9&lK&f&lSHOP &7: &r기본 콘피그를 다시 불러왔습니다.'
ShopReloadShop: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a을 다시 불러왔습니다.'
ShopItemSetDone: '&6&lH&9&lK&f&lSHOP &7: &a상점 &r{SHOPNAME} &a의 아이템설정이 완료되었습니다.'
EnterInteger: '&6&lH&9&lK&f&lSHOP &7: &c정수를 입력하세요 ex) 100, 1000'
ShopPriceSetStart: '&6&lH&9&lK&f&lSHOP &7: &6구매가를 채팅으로 입력하세요. (0이하로 입력시 금지됨)'
ShopPriceSetting: '&6&lH&9&lK&f&lSHOP &7: &6판매가를 채팅으로 입력하세요. (0이하로 입력시 금지됨)'
ShopPriceSetDone: '&6&lH&9&lK&f&lSHOP &7: &6상점 &r{SHOPNAME} &6의 가격설정이 완료되었습니다. &f( &a{SHOPBUY} &7/ &c{SHOPSELL} &f)'
UnknownCommand: '&6&lH&9&lK&f&lSHOP &7: &c알 수 없는 명령어 입니다. &f/상점관리'

ShopManage:
  - ' '
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 리로드 - 기본 콘피그를 리로드합니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 열기 [이름] - 상점을 오픈합니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 생성 [이름] - 상점을 생성합니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 삭제 [이름] - 상점을 삭제합니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 아이템설정 [이름] - 상점에 올릴 아이템을 설정합니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 가격설정 [이름] - 상점에 올린 아이템의 가격을 설정합니다.'
  - '   &f┗ 채팅창에 금액을 입력하며 0 이하로 입력시 구매/판매가 금지됩니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 줄설정 [줄] [이름] - 상점 GUI의 사이즈를 조절합니다.'
  - '   &6&lH&9&lK&f&lSHOP &7: &f/상점관리 NPC등록 [이름] - 상점을 열 NPC를 등록합니다.'

OpenShop: '   &6&lH&9&lK&f&lSHOP &7: &b상점 &r{SHOPNAME} &b을 열었습니다.'
LackMoney: '   &6&lH&9&lK&f&lSHOP &7: &c돈이 부족합니다. &6현재 남은 돈 &7: &f{LEFTMONEY}&6원'
LackItem: '   &6&lH&9&lK&f&lSHOP &7: &c해당 아이템을 가지고 있지 않습니다.'
BannedBuy: '   &6&lH&9&lK&f&lSHOP &7: &c해당 아이템은 구매할 수 없습니다.'
BannedSell: '   &6&lH&9&lK&f&lSHOP &7: &c해당 아이템은 판매할 수 없습니다.'
BuyItems: '   &6&lH&9&lK&f&lSHOP &7: &a아이템 &6{NUM}&a개를 구매하였습니다. &6현재 남은 돈 &7: &f{LEFTMONEY}&6원'
SellItems: '   &6&lH&9&lK&f&lSHOP &7: &c아이템 &6{NUM}&c개를 판매하였습니다. &6현재 남은 돈 &7: &f{LEFTMONEY}&6원'